# Gunakan Node.js versi LTS
FROM node:lts

# Set working directory
WORKDIR /app

# Salin package.json dan install dependencies
COPY package*.json ./
RUN npm install

# Salin semua file
COPY . .

# Ekspos port
EXPOSE 3000

# Jalankan aplikasi
CMD ["node", "index.js"]
